[package]
name = "rust-signals-issue-broadcaster-deadlock"
version = "0.0.0"
edition = "2021"
authors = ["Cameron <cameron@drivenow.com.au>"]

[dependencies]
tokio = { version = "1.0", features = ["rt-multi-thread", "macros", "sync", "time","full"] }
futures-signals = "=0.3.34"
simple_logger = "*"